name: Code validation
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.0.0
    - name: Build
      run: go build -v ./...

  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.0.0
      - name: golangci-lint
        uses: actions-contrib/golangci-lint@v1
        with:
          args: run

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.0.0
    - name: Run Unit tests.
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
    - name: Upload Coverage report to CodeCov
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.txt
